name: Node demo service ci/cd
on:
  workflow_call:
    inputs:
      environment:
        description: "Deployment Environment"
        required: true
        type: string

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Set short SHA output
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set Helm env
        id: helm_env
        run: |
          echo "helm_environment=${{ inputs.environment }}" >> $GITHUB_OUTPUT
          echo branch: ${{ github.head_ref || github.ref_name }}
          echo environment: ${{ inputs.environment }}

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Build, tag, and push the API Docker image
      - name: Build, tag, and push API Docker image to docker hub
        env:
          REGISTRY: shuvo85cisco
          REPOSITORY: node-demo
          IMAGE_TAG: ${{ steps.vars.outputs.sha_short }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f DockerFile.api .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
     
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      #   with:
      #     images: shuvo85cisco/node-demo

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      #   with:
      #     context: .
      #     file: Dockerfile
      #     push: true
      #     tags: ${{ steps.vars.outputs.sha_short }}
      #     labels: ${{ steps.meta.outputs.labels }}
