name: Production Node Demo

concurrency:
  group: 'production'
  cancel-in-progress: true

on:
  push:
    branches:    
      - 'main'     

  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/build-deploy.yml
    with:
      environment: "production"
    secrets: inherit