name: Staging Node Demo

concurrency:
  group: 'staging'
  cancel-in-progress: true

on:
  push:
    branches:    
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'

  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/build-deploy.yml
    with:
      environment: "staging"
    secrets: inherit